name: CD - Deploy to Cloud Run 

on:
  push: [" main "]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1 - Auth Google Cloud via WIF
      - name: Auth to GCP   
        uses: google-github-actions/auth@v2   
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      # Step 2 - Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Step 3 - Docker auth an Artifact Registry
      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
      
      # Step 4 - Build and Push a Artifact Registry
      - name: Build and Push image
        
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          AR_REPO: ${{ secrets.AR_REPO}}
        
        run: |
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/api-comics:${GITHUB_SHA}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Step 5 - Deploy a Cloud Run (with Cloud SQL)
      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
          CLOUDSQL: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          # DATABASE_URI via Cloud SQL socket
          DATABASE_URI="postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@/${POSTGRES_DB}?host=/cloudsql/${CLOUDSQL}"

          gcloud run deploy "$SERVICE" \
            --project="$PROJECT_ID" \
            --region="$REGION" \
            --image="$IMAGE" \
            --add-cloudsql-instances="$CLOUDSQL" \
            --set-env-vars="DATABASE_URI=${DATABASE_URI},FLASK_APP=main:create_app" \
            --allow-unauthenticated

